### ISSUE TITLE
This completely bricked LoL on my PC

### ISSUE THREAD

**Issue by ConsentKF** [KebsCS/KBotExt#38] opened 2022-07-12 02:42 UTC
I installed KBotExt and used it to run league, afterwards I closed Kbot and tried to run league on it's own and it would turn on Kbot, which I did not want. I removed Kbotext from my computer and League stopped working after logging in. The client opens fine, but after I log in and click Play the process ends. I've restarted my PC several times and uninstalled + clean installed league and nothing works, I cannot play the game anymore. How do I fix this?

edit: checked the logs and found this:

000000.363|  ERROR| Failed to start UX process C:/Riot Games/League of Legends/LeagueClientUx.exe.

Manually running LeagueClientUx gives windows error "Windows cannot find ... Make sure you typed the name correctly and then try again." 

It's in the Riot Games folder but is not being recognized by Windows anymore? :\

**Comment by KebsCS** [comment] 2022-07-13 10:58
Duplicate of #29

**Closed by KebsCS** 2022-07-13 10:58 UTC
