### ISSUE TITLE
Lobby Reveal Failing to get Region

### ISSUE THREAD

**Issue by RJGY** [KebsCS/KBotExt#185] opened 2023-09-18 09:45 UTC
Tried clicking the multisearch and it failed, see screenshot below. Region should be OCE by the way. Reinstalled and had the same issue. Not sure whats going wrong.
![image](https://github.com/KebsCS/KBotExt/assets/54159414/adea8280-47b6-496d-8440-5fd21f0949d6)

**Comment by S1ro1** [comment] 2023-09-18 10:34
With u.gg it works, all other fail

**Comment by RJGY** [comment] 2023-09-18 11:00
Ah, thanks for that. Will use u.gg for the time being until it is fixed for OP.GG and other sites.

**Comment by S1ro1** [comment] 2023-09-18 11:48
Also it is already fixed in pre-release i just noticed

**Comment by BennyExtreme** [comment] 2023-09-18 15:06
Yes, this issue is basically a duplicate of #181 #182.
I fixed it with PR #184.

> Also it is already fixed in pre-release i just noticed

For now, a new version has not been released so you will not receive any notifications within the program.
However, this repository has an action that automatically compiles the latest changes into a pre-release so, yes you can use that and it's fixed in that version.

**Comment by RJGY** [comment] 2023-09-18 16:10
My bad, didnt look at the previous issue posts. Will take a look at the prereleases. Thanks

**Closed** 2023-11-21 18:42 UTC
