### ISSUE TITLE
HttpSendRequestA failed. Last error: 6

### ISSUE THREAD

**Issue by Imploree** [KebsCS/KBotExt#15] opened 2021-08-03 14:01 UTC
Hello!!
thx for the programe
i dont know if the probleme its the new patch in league 11.15 and i have windows 7
because when i try any option in this programe it show me this message error "HttpSendRequestA failed. Last error: 6"
![1](https://user-images.githubusercontent.com/88387933/128030847-6ee112d1-7ee3-4cca-848c-84dbb0189ebe.png)

**Comment by KebsCS** [comment] 2021-08-03 17:53
Duplicate of https://github.com/KebsCS/KBotExt/issues/3 and fixed in https://github.com/KebsCS/KBotExt/commit/6cce672b390e33722595901cc0d7d32fcd786fe9

**Closed by KebsCS** 2021-08-03 17:53 UTC
